version: '3'
services:
  broker:
    image: "rabbitmq:3-management"
    hostname: "broker"
    labels:
      NAME: "some-rabbit"
    environment:
      PYTHONBUFFERED: 0
  consumer:
    build: .
    depends_on:
      - "broker"
    #wait-for-it is used to check if rabbit is stable.
    command: >
      sh -c "curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -s --output wait-for-it.sh
      && chmod +x wait-for-it.sh
      &&./wait-for-it.sh my-rabbit:5672
      && poetry run consumer"
  producer:
    build: .
    depends_on:
      - "broker"
    command: >
      sh -c "curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -s --output wait-for-it.sh
      && chmod +x wait-for-it.sh
      &&./wait-for-it.sh my-rabbit:5672
      && poetry run producer"
