version: '3'
services:
  broker:
    image: "rabbitmq:3"
    hostname: "broker"
    labels:
      NAME: "rabbit-broker"
    environment:
      PYTHONBUFFERED: 1 
  consumer:
    build: .
    depends_on:
      - "broker"
    command: >
      sh -c "./wait-for-it.sh broker:5672
      && poetry run consumer"
    volumes:
      - ./:/usr/src/app/export
  producer:
    build: .
    depends_on:
      - "broker"
    command: >
      sh -c "./wait-for-it.sh broker:5672
      && poetry run producer"
