version: '3'
services:
  my-rabbit:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit"
    labels:
      NAME: "some-rabbit"
    environment:
      PYTHONBUFFERED: 0
  consumer:
    build: consumer/.
    depends_on:
      - "my-rabbit"
  producer:
    build: producer/.
    depends_on:
      - "my-rabbit"
